### ISSUE TITLE
Code Concern

### ISSUE THREAD

**Issue by clarkpanares** [MisterBianco/wifijammer-ng#4]
Hi MisterBianco, I would like to kindly ask on your time to teach me how to integrate the script with a database containing mac address to be exempted while blocking an specific channel. If ever, what could be your email so I can send my other concerns about this. I'm currently studying python and it will be really helpful for me if you could help me. TIA

**Comment by MisterBianco** [comment]
You can email me @ jayrad.security@protonmail.com however if you don't have experience with databases I won't be able to help you much.
